version: '2'
services:
 zabbix-server:
  image: server-nginx-php
#  networks:
#   - bridge
  ports:
   - "10051:10051"
   - "80:80"
  links:
   - mariadb:mysql-server
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
   mem_limit: 512m
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=eastspider
    - MYSQL_DATABASE=zabbix
    - TZ=Asia/Shanghai
    - ZBX_SERVER_HOST=zabbix-server
    - DB_SERVER_HOST=mysql-server
    - ZBX_HOUSEKEEPINGFREQUENCY=1
    - ZBX_MAXHOUSEKEEPERDELETE=5000
    - ZBX_SENDERFREQUENCY=30
    - ZBX_CACHESIZE=8M
    - ZBX_CACHEUPDATEFREQUENCY=60
    - ZBX_STARTDBSYNCERS=4
    - ZBX_HISTORYCACHESIZE=16M
    - ZBX_HISTORYINDEXCACHESIZE=4M
    - ZBX_TRENDCACHESIZE=4M
    - ZBX_VALUECACHESIZE=8M
  user: root
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 mariadb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=eastspider
  ports:
   - "3306:3306"

networks:
   default:
      driver: bridge
